#!/bin/bash

install_file=google_install.sh
credentials_file="$HOME/.config/gcloud/application_default_credentials.json"
bashrc="$HOME/.bashrc"

# Install required dependencies for gcloud SDK.
sudo apt-get install software-properties-common python3 -y

# Download SDK installer.
curl https://sdk.cloud.google.com > $install_file

# Remove previous installation.
rm -rf "$HOME/google-cloud-sdk"
sudo chown -R $USER "$HOME/.config/gcloud"

# Run the installer.
bash $install_file

# Remove the installer file.
rm $install_file

# Apply changes to PATH.
source "$HOME/.bashrc"

# Initialize the account and the credentials.
gcloud init
gcloud auth application-default login

# Create credentials environment variable if it doesn't already exist.
if ! grep -q GOOGLE_APPLICATION_CREDENTIALS "$bashrc"; then
  echo "export GOOGLE_APPLICATION_CREDENTIALS=$credentials_file" > "$bashrc"
fi