on:
  push:
    branches:
      - master
    paths:
      - ./**/*.go
  pull_request:
    branches:
      - master
    paths:
      - ./**/*.go
name: Backend
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .devcontainer/docker-compose.yml
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Format
        uses: Jerome1337/goimports-action@v1.0.3
      - name: Lint
        uses: golangci/golangci-lint-action@v2
      - name: Test
        run: docker-compose exec dev go test -v ./...
